clip_0: 6      # initial_cameraAngle
clip_1: 7      # initial_shotSize
clip_2: 5.5    # initial_subjectView
clip_3: 5.5    # initial_subjectFraming
clip_4: 7.5    # movement_type
clip_5: 5      # movement_speed
clip_6: 8      # final_cameraAngle
clip_7: 9.5    # final_shotSize
clip_8: 6      # final_subjectView
clip_9: 10     # final_subjectFraming
clip_10: 4     # setup_config_cameraAngle
clip_11: 5     # setup_config_shotSize
clip_12: 5     # setup_config_subjectView
clip_13: 4.5   # setup_config_subjectFraming_position
clip_14: 1     # setup_config_subjectFraming_dutchAngleScale
clip_15: 1     # setup_kind
clip_16: 2     # dynamic_type
clip_17: 4.5   # dynamic_easing
clip_18: 1     # dynamic_randomness
clip_19: 4.5   # dynamic_complementSetup_cameraAngle
clip_20: 6.5   # dynamic_complementSetup_shotSize
clip_21: 3.5   # dynamic_complementSetup_subjectView
clip_22: 6     # dynamic_complementSetup_subjectFraming_position
clip_23: 1.5   # dynamic_complementSetup_subjectFraming_dutchAngleScale
clip_24: 1     # dynamic_subjectAwareInterpolation
clip_25: 2.5   # dynamic_scale
clip_26: 3.5   # dynamic_direction
clip_27: 3     # dynamic_movementMode
clip_28: 1     # constraints_allFramesVisibility
clip_29: 1     # constraints_staticDistance
clip_30: 1     # constraints_staticCameraSubjectRotation
clip_31: 1     # constraints_lockedMovement_left
clip_32: 1     # constraints_lockedMovement_right
clip_33: 1     # constraints_lockedMovement_up
clip_34: 1     # constraints_lockedMovement_down
clip_35: 1     # constraints_lockedMovement_forward
clip_36: 1     # constraints_lockedMovement_backward
clip_37: 1     # constraints_lockedRotation_left
clip_38: 1     # constraints_lockedRotation_right
clip_39: 1     # constraints_lockedRotation_up
clip_40: 1     # constraints_lockedRotation_down
clip_41: 1     # constraints_lockedRotation_rollClockwise
clip_42: 1     # constraints_lockedRotation_rollNonClockwise
clip_43: 1     # constraints_maxAccelerate
clip_44: 1     # constraints_maxSpeed
clip_45: 1     # constraints_importance
