run:
  dir: ${oc.env:OUTPUT_DIR,outputs}/${now:%Y-%m-%d}/${now:%H-%M-%S}
sweep:
  dir: ${oc.env:OUTPUT_DIR,outputs}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
  subdir: ${hydra.job.num}
job:
  chdir: True

sweeper:
  sampler:
    _target_: optuna.samplers.TPESampler
    seed: ${seed}
    multivariate: true

  n_trials: 300
  direction: minimize
  storage: sqlite:///optuna_camera_traj.db
  study_name: camera-traj-optimized
  n_jobs: 4

  params:
    training.model.module.num_encoder_layers: choice(4, 7, 10)
    training.model.module.num_decoder_layers: choice(4, 7, 10)
    training.model.module.nhead: choice(4, 8, 16)
    training.model.module.dim_feedforward: choice(1024, 2048, 4096)
    training.model.module.dropout_rate: interval(0.1, 0.5)
    
    trainer.max_epochs: 1
    data.batch_size: choice(32, 64, 128)
    data.num_workers: 0

    
    training.optimizer.lr: tag(log, interval(5e-8, 5e-4))
    training.optimizer.weight_decay: tag(log, interval(1e-5, 0.2))
    training.optimizer.betas.0: interval(0.85, 0.95)
    training.optimizer.betas.1: interval(0.9, 0.999)
    
    training.loss_module.losses_list.clip: interval(200, 1000)
    training.loss_module.losses_list.first_frame: interval(0, 10)
    training.loss_module.losses_list.relative: interval(0, 25)
    training.loss_module.losses_list.speed: interval(0, 200)
    training.loss_module.losses_list.cycle: interval(0, 500)
    # training.loss_module.losses_list.contrastive: interval(5, 25)
    # training.loss_module.contrastive_loss_margin: interval(1, 15)


    training.lr_scheduler.warmup_steps: choice(5, 10, 15)
    training.lr_scheduler.rate: interval(0.4, 0.9)
    training.lr_scheduler.n_th_root: choice(1, 2, 3)
    
    training.noise.initial_std: interval(0.3, 2.5)
    training.noise.final_std: interval(0, 0.3)
    
    training.mask.initial_ratio: interval(0.05, 0.2)
    training.mask.final_ratio: interval(0.6, 0.9)
    
    training.teacher_forcing_schedule.memory_initial_ratio: interval(0.2, 0.7)
    training.teacher_forcing_schedule.memory_final_ratio: interval(0.7, 1.0)
    # training.teacher_forcing_schedule.trajectory_initial_ratio: interval(0.7, 1.0)
    # training.teacher_forcing_schedule.trajectory_final_ratio: interval(0.0, 0.3)
  