data_format: 
  type: simulation
  seq_length: 30

module:
  _target_: models.camera_trajectory_model.MultiTaskAutoencoder
  input_dim: 6
  subject_dim: 6
  nhead: 8
  num_encoder_layers: 4
  num_decoder_layers: 4
  dim_feedforward: 2048
  dropout_rate: 0.3
  seq_length: ${training.model.data_format.seq_length}
  latent_dim: ${clip.latent_dim}
  use_merged_memory: ${training.use_merged_memory}
  denormalize_memory: false