defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    study_name: camera_trajectory_optimization
    storage: null
    n_trials: 20
    n_jobs: 1
    params:
      training.model.nhead: choice(4, 8, 16)
      training.model.num_encoder_layers: choice(2, 4, 6)
      training.model.num_decoder_layers: choice(2, 4, 6)
      training.model.dim_feedforward: choice(1024, 2048, 4096)
      training.model.dropout_rate: interval(0.1, 0.5)
      
      training.optimizer.lr: tag(log, interval(1e-5, 1e-3))
      training.optimizer.weight_decay: tag(log, interval(0.01, 0.2))
      
      training.lr_scheduler.warmup_steps: choice(5, 10, 20)
      training.lr_scheduler.rate: interval(0.4, 0.7)
      
      data.batch_size: choice(32, 64, 128)
      training.noise.initial_std: interval(0.5, 1.5)
      training.mask.initial_ratio: interval(0.05, 0.2)
      training.mask.final_ratio: interval(0.6, 0.9)
      
      training.loss_module.trajectory_loss_ratio: interval(5, 15)
      training.loss_module.clip_loss_scaling_factor: interval(20000, 50000)
