batch_size: 32
epochs: 20
patience: 30

optimizer_config:
  lr: 0.0001
  weight_decay: 1e-5
  init_teacher_forcing_ratio: 0.8
  initial_noise_std: 0.2
  final_noise_std: 0.05
  initial_mask_ratio: 0.3
  final_mask_ratio: 0.7
