_target_: training.autoencoder_trainer.LightningMultiTaskAutoencoder

defaults:
  - model: default
  - optimizer: adamW
  - lr_scheduler: linear_warmup_cosine

noise:
  initial_std: 0.1
  final_std: 0.05

mask:
  initial_ratio: 0.1
  final_ratio: 0.5

teacher_forcing_schedule:
  initial_ratio: 0.9
  final_ratio: 0.1
