batch_size: 32
device: "cpu"
epochs: 20
final_mask_ratio: 0.7
final_noise_std: 0.05
init_teacher_forcing_ratio: 0.8
initial_mask_ratio: 0.3
initial_noise_std: 0.2
lr: 0.0001
patience: 30
weight_decay: 1e-5
seed: 42
