_target_: training.autoencoder_trainer.LightningMultiTaskAutoencoder

defaults:
  - model: default
  - optimizer: adam
  - lr_scheduler: cosine

noise:
  initial_std: 0.2
  final_std: 0.05

mask:
  initial_ratio: 0.3
  final_ratio: 0.7

teacher_forcing_schedule:
  initial_ratio: 0.9
  final_ratio: 0.1
