defaults:
  - _self_
  - clip: default
  - data: default
  - training: default
  - hydra: default
  - sim_model: default

output:
  batch_dir: ${oc.env:BATCH_DIR,./batch_files}
  results_dir: ${oc.env:RESULTS_DIR,./batch_results}
  annotations_dir: ${oc.env:ANNOTATIONS_DIR,./cinematography_annotations}


num_batches: 100

api:
  model: gpt-4.1-nano
  max_batch_size: 1000
  poll_interval: 300
