defaults:
  - model: default
  - training: default
  - data: mini
  - output: default
  - clip: default
  - _self_

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

dataset:
  _target_: data.simulation.dataset.SimulationDataset
  data_path: ${data.data_path}
  clip_embeddings:
    _target_: models.clip_embeddings.initialize_all_clip_embeddings
    clip_model_name: ${clip.model_name}

lightning_model:
  _target_: training.autoencoder_trainer.LightningMultiTaskAutoencoder
  model: ${model}
  optimizer_config: ${training.optimizer_config}

callbacks:
  early_stopping:
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: val_loss
    patience: ${training.patience}
    mode: min
  model_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    monitor: val_loss
    filename: best-model-{epoch:02d}-{val_loss:.2f}
    save_top_k: 1
    mode: min

trainer:
  _target_: lightning.Trainer
  max_epochs: ${training.epochs}
  accelerator: auto
  devices: auto
