defaults:
  - training: default
  - trainer: default
  - data: default
  - output: default
  - clip: default
  - hydra: default
  - _self_

seed: 42
patience: 100

callbacks:
  early_stopping:
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: val_loss
    patience: ${patience}
    mode: min
  model_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    monitor: val_loss
    filename: best-model-{epoch:02d}-{val_loss:.2f}
    save_top_k: 1
    mode: min
  lr_monitor:
    _target_: lightning.pytorch.callbacks.LearningRateMonitor
    logging_interval: "step"

compile:
  enabled: false
  mode: "default"
