defaults:
  - _self_
  - clip: default
  - data: default
  - training: default
  - hydra: default

checkpoint_path: lightning_logs/version_33/checkpoints/best-train-model-epoch=079-train_loss=0.164.ckpt
output_dir: inference_results

sample_id: null # If null, process all samples
text_prompt: null # If null and sample has caption, will use sample caption

device: cuda
