defaults:
  - _self_
  - clip: default
  - data: default
  - training: default
  - hydra: default
  - override data/dataset: et

checkpoint_path: lightning_logs/version_3/checkpoints/best-model-epoch=21-val_loss=1.15.ckpt
output_dir: inference_results

sample_id: null # If null, process all samples
text_prompt: null # If null and sample has caption, will use sample caption

device: cuda
