defaults:
  - _self_
  - clip: default
  - data: default
  - training: default
  - hydra: test

output_dir: ${oc.env:TEST_OUTPUT_DIR,./test_results}
device: cuda

# Absolute number of visible, valid camera frames in keyframing modes.
num_keyframes: 4
