defaults:
  - _self_
  - clip: default
  - data: default
  - training: default
  - hydra: default

model_config:
  type: simulation
  checkpoint_path: ${oc.env:TEST_CHECKPOINT_PATH}

output_dir: ${oc.env:TEST_OUTPUT_DIR,./test_results}
device: cuda

caption_top1_metric: true
clip_embeddings_cache: ${oc.env:CLIP_EMBEDDINGS_CACHE_DIR,.}/clip_embeddings_${clip.model_name}_cache.pkl
