defaults:
  - _self_
  - clip: default
  - data: default
  - training: default
  - hydra: default

sim_model: 
  module: ${training.sim_model.module}
  inference: ${training.sim_model.inference}

output_dir: ${oc.env:TEST_OUTPUT_DIR,./test_results}
device: cuda

caption_top1_metric: false
