defaults:
  - _self_
  - clip: default
  - data: default
  - training: default
  - hydra: test
  - ref_model: default

output_dir: ${oc.env:TEST_OUTPUT_DIR,./test_results}
cache_dir: ${oc.env:CACHE_DIR}
device: cuda
tsne: false

caption_top1_metric: false
baseline_norm_ablation: true

clatr_backend: native
clatr_native_checkpoint_path: ${oc.env:CLATR_NATIVE_CHECKPOINT_PATH,null}
clatr_checkpoint_path: ${oc.env:CLATR_CHECKPOINT_PATH,null}
