defaults:
  - _self_
  - clip: default
  - data: default
  - training: default
  - hydra: default

checkpoint_path: ${oc.env:INFERENCE_CHECKPOINT_PATH}
output_dir: ${oc.env:INFERENCE_OUTPUT_DIR,./inference_results}

device: cuda
