defaults:
  - _self_
  - clip: default
  - data: default
  - training: default
  - hydra: test
  - ref_model: default

output_dir: ${oc.env:TEST_OUTPUT_DIR,./test_results}
cache_dir: ${oc.env:CACHE_DIR}
device: cuda

caption_top1_metric: false
