defaults:
  - _self_
  - hydra: default

logdir: ${oc.env:TENSORBOARD_LOG_DIR,lightning_logs/version_133}
save_plot: ${oc.env:PLOT_SAVE_PATH,./visualization/tensorboard_plot_}

plot:
  figsize:
    width: 23
    height: 18
  style:
    plt_style: "bmh"
    major_grid_style: 
      which: "major"
      linestyle: "-"
      linewidth: 1.0
      alpha: 1.0
      color: "#4a4a4a"
    minor_grid_style:
      which: "minor"
      linestyle: "--"
      linewidth: 0.7
      alpha: 0.75
      color: "#828282"
    title: "Training and Validation Metrics"
    title_params:
      fontsize: 34
      fontweight: "bold"
      pad: 20
      y: 1.01
    xlabel: "Step"
    ylabel: "Value"
    labelpad: 20
    suptitle_font_size: 42
    title_font_weight: "bold"
    suptitle_font_weight: "bold"
    font_size: 26
    font_family: "MathJax_SansSerif"
    apply_fixed_ylim_clip: true
    suptitle_offset: 0.995
    xticks_pad: 15
    yticks_pad: 15
    border_color: "black"
    border_linewidth: 1
  n_cols: 3
  tight_layout: true

metrics:
  losses_list:
    - clip
    - trajectory
    # - contrastive # TODO: not yet completed
  validation:
    - val_loss_epoch
    - val_trajectory_epoch
    - val_total_epoch
  training:
    - train_loss_epoch
    - train_trajectory_epoch
    - train_total_epoch
  clips:
    num_clips: 28 
    categorize_embeddings: true
    average_clip_loss: true # to enable this option, 'clip' should be in 'losses_list'
    include_validation: true
    include_training: true
  

event_accumulator:
  size_guidance:
    scalars: 0
    histograms: 0
    images: 0
    tensors: 0

output:
  show_plot: false
  save_plot: true
  print_available_tags: false
  plot_format: "png"
  dpi: 100
  
line_styles:
  training:
    linestyle: "--"
    linewidth: 2.5
    alpha: 0.4
  validation:
    linestyle: "-"
    linewidth: 2.5
    alpha: 1.0


legend:
  loc: "upper center"
  fontsize: 20
  frameon: true
  framealpha: 0.8
  bbox_to_anchor: [0.5, -0.15]
  ncol: 3
  shadow: true
  fancybox: true
  borderpad: 1.2


color_map:
  clip_loss: 
  # Cinematography Prompt:
    # Initial:
    - clip_0:  "#E9C46A" 
    - clip_1:  "#2A9D8F"
    - clip_2:  "#E63946"
    - clip_3:  "#9B5DE5"
    # Movement: 
    - clip_4:  "#457B9D"
    - clip_5:  "#9B5DE5"
    # Final: Red
    - clip_6:  "#E63946" 
    - clip_7:  "#F4A261"
    - clip_8:  "#E9C46A"
    - clip_9:  "#2A9D8F"
  # Simulation Instruction:
    # Initial Setup: 
    - clip_10: "#E63946"
    - clip_11: "#9B5DE5"
    - clip_12: "#E9C46A"
    - clip_13: "#2A9D8F"
    - clip_14: "#457B9D"
    # Dynamic: 
    - clip_15: "#E63946" 
    - clip_16: "#F4A261"
    - clip_17: "#E9C46A"
    - clip_18: "#DA70D6"
    - clip_19: "#457B9D"
    - clip_20: "#9B5DE5" 
    - clip_21: "#D08C60" 
    - clip_22: "#00A896" 
    - clip_23: "#F4D35E" 
    - clip_24: "#5E60CE" 
    # Constraints: 
    - clip_25: "#E63946" 
    - clip_26: "#2A9D8F" 
    - clip_27: "#5E60CE" 
  trajectory_loss:
    - los: "#457B9D"
    - trajectory: "#D08C60"
    - total: "#E63946"  

clip_structure:
  cinematography:
    initial:       # parameter:
      - clip_0     # initial_cameraAngle
      - clip_1     # initial_shotSize
      - clip_2     # initial_subjectView
      - clip_3     # initial_subjectFraming
    movement:      #   
      - clip_4     # movement_type
      - clip_5     # movement_speed
    final:         #   
      - clip_6     # final_cameraAngle
      - clip_7     # final_shotSize
      - clip_8     # final_subjectView
      - clip_9     # final_subjectFraming
  simulation:      #    
    initial_setup: #   
      - clip_10    # initialSetup_cameraAngle
      - clip_11    # initialSetup_shotSize
      - clip_12    # initialSetup_subjectView
      - clip_13    # initialSetup_subjectFraming_position
      - clip_14    # initialSetup_subjectFraming_dutchAngleScale
    dynamic:       #   
      - clip_15    # dynamic_easing
      - clip_16    # dynamic_endSetup_cameraAngle
      - clip_17    # dynamic_endSetup_shotSize
      - clip_18    # dynamic_endSetup_subjectView
      - clip_19    # dynamic_endSetup_subjectFraming_position
      - clip_20    # dynamic_endSetup_subjectFraming_dutchAngleScale
      - clip_21    # dynamic_endSetup_subjectAwareInterpolation
      - clip_22    # dynamic_scale
      - clip_23    # dynamic_direction
      - clip_24    # dynamic_movementMode
    constraints:   #   
      - clip_25    # constraints_allFramesVisibility
      - clip_26    # constraints_staticDistance
      - clip_27    # constraints_staticCameraSubjectRotation